import {
  Activity,
  BarChart3,
  BookOpen,
  Brain,
  Check,
  Cloud,
  Code2,
  Compass,
  GitFork,
  HeartPulse,
  KeyRound,
  Layers,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Target,
  TrendingUp,
  Truck,
  Users,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  "code-2": Code2,
  cloud: Cloud,
  smartphone: Smartphone,
  compass: Compass,
  "map-pin": MapPin,
  mail: Mail,
  "shield-check": ShieldCheck,
  check: Check,
  target: Target,
  "book-open": BookOpen,
  activity: Activity,
  "key-round": KeyRound,
  layers: Layers,
  lock: Lock,
  "git-fork": GitFork,
  "shopping-bag": ShoppingBag,
  brain: Brain,
  "bar-chart-3": BarChart3,
  "message-circle": MessageCircle,
  truck: Truck,
  "shopping-cart": ShoppingCart,
  users: Users,
  "heart-pulse": HeartPulse,
  "trending-up": TrendingUp,
};

export function NamedIcon({ name, className }: { name: string; className?: string }) {
  const Icon = MAP[name] ?? Code2;
  return <Icon className={className} strokeWidth={1.8} />;
}
